-- IAQ V1.0 persistence contract. Run this in PostgreSQL through Alembic in production.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text UNIQUE NOT NULL, role text NOT NULL CHECK (role IN ('student','guardian','counselor','reviewer','admin')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), display_name text NOT NULL, age_band text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS consents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), consent_version text NOT NULL, purpose text NOT NULL, granted boolean NOT NULL, recorded_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS constructs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), construct_id text UNIQUE NOT NULL, name text NOT NULL, definition text NOT NULL, review_status text NOT NULL DEFAULT 'psychometric_review_required');
CREATE TABLE IF NOT EXISTS item_families (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), family_id text UNIQUE NOT NULL, domain text NOT NULL, rules jsonb NOT NULL DEFAULT '{}'::jsonb, lifecycle_status text NOT NULL DEFAULT 'DRAFT');
CREATE TABLE IF NOT EXISTS items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), item_id text UNIQUE NOT NULL, item_family_id uuid REFERENCES item_families(id), domain text NOT NULL, lifecycle_status text NOT NULL, data_origin text NOT NULL CHECK (data_origin IN ('REVIEWED_CONTENT','SYNTHETIC')), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS item_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), item_id uuid NOT NULL REFERENCES items(id), version integer NOT NULL, prompt text NOT NULL, answer_key text NOT NULL, options jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(item_id, version));
CREATE TABLE IF NOT EXISTS item_reviews (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), item_version_id uuid NOT NULL REFERENCES item_versions(id), reviewer_id uuid REFERENCES users(id), status text NOT NULL, notes text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS assessment_definitions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text UNIQUE NOT NULL, name text NOT NULL);
CREATE TABLE IF NOT EXISTS assessment_versions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), definition_id uuid NOT NULL REFERENCES assessment_definitions(id), version text UNIQUE NOT NULL, scoring_model_version text NOT NULL, norm_version text, status text NOT NULL);
CREATE TABLE IF NOT EXISTS test_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), assessment_version_id uuid NOT NULL REFERENCES assessment_versions(id), status text NOT NULL, data_origin text NOT NULL DEFAULT 'REAL_PILOT', started_at timestamptz, completed_at timestamptz);
CREATE TABLE IF NOT EXISTS responses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), session_id uuid NOT NULL REFERENCES test_sessions(id), item_version_id uuid NOT NULL REFERENCES item_versions(id), presented_order integer NOT NULL, response jsonb NOT NULL, is_correct boolean NOT NULL, response_time_ms integer, idempotency_key text UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS session_quality_flags (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), session_id uuid NOT NULL REFERENCES test_sessions(id), flag text NOT NULL, severity text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS domain_scores (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), session_id uuid NOT NULL REFERENCES test_sessions(id), domain text NOT NULL, score numeric NOT NULL, standard_error numeric, score_version text NOT NULL);
CREATE TABLE IF NOT EXISTS assessment_results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), session_id uuid UNIQUE NOT NULL REFERENCES test_sessions(id), composite numeric NOT NULL, confidence text NOT NULL, disclaimer text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS questionnaires (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text UNIQUE NOT NULL, name text NOT NULL);
CREATE TABLE IF NOT EXISTS questionnaire_responses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), questionnaire_id uuid NOT NULL REFERENCES questionnaires(id), user_id uuid NOT NULL REFERENCES users(id), responses jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS interest_profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), code text NOT NULL, scores jsonb NOT NULL, version text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS academic_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), subject text NOT NULL, result text, evidence_origin text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS student_activities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), title text NOT NULL, activity_type text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS major_families (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), slug text UNIQUE NOT NULL, name text NOT NULL);
CREATE TABLE IF NOT EXISTS major_profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), major_family_id uuid NOT NULL REFERENCES major_families(id), name text NOT NULL, source_reviewed_at timestamptz, vector jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS major_sources (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), major_profile_id uuid NOT NULL REFERENCES major_profiles(id), url text NOT NULL, source_type text NOT NULL, reviewed_at timestamptz);
CREATE TABLE IF NOT EXISTS major_matches (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), major_profile_id uuid NOT NULL REFERENCES major_profiles(id), fit numeric NOT NULL, readiness numeric NOT NULL, feasibility text NOT NULL, confidence numeric NOT NULL, recommendation_version text NOT NULL);
CREATE TABLE IF NOT EXISTS exploration_templates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), major_profile_id uuid REFERENCES major_profiles(id), title text NOT NULL, steps jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS student_explorations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), template_id uuid REFERENCES exploration_templates(id), status text NOT NULL, started_at timestamptz, completed_at timestamptz);
CREATE TABLE IF NOT EXISTS student_reflections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), exploration_id uuid REFERENCES student_explorations(id), body text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS counselor_access (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), counselor_id uuid NOT NULL REFERENCES users(id), student_id uuid NOT NULL REFERENCES users(id), granted boolean NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS counselor_notes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), counselor_id uuid NOT NULL REFERENCES users(id), student_id uuid NOT NULL REFERENCES users(id), note text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), actor_id uuid REFERENCES users(id), action text NOT NULL, resource_type text NOT NULL, resource_id uuid, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS deletion_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id), status text NOT NULL DEFAULT 'requested', created_at timestamptz NOT NULL DEFAULT now());

CREATE INDEX IF NOT EXISTS responses_session_idx ON responses(session_id);
CREATE INDEX IF NOT EXISTS domain_scores_session_idx ON domain_scores(session_id);
CREATE INDEX IF NOT EXISTS audit_logs_resource_idx ON audit_logs(resource_type, resource_id);
