import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { getInterestQuestionnaire, getInterestResult, issueCertificate, listCertificates, submitInterestResponses, verifyCertificate, type Certificate, type InterestItem, type InterestResult } from './api'

function ProductIntro({ eyebrow, title, body }: { eyebrow: string; title: React.ReactNode; body: string }) {
  return <div className="page-intro"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="lede">{body}</p></div></div>
}

export function InterestAssessment({ resultId }: { resultId?: string }) {
  const [items, setItems] = useState<InterestItem[]>([])
  const [ratings, setRatings] = useState<Record<string, number>>({})
  const [result, setResult] = useState<InterestResult | null>(null)
  const [status, setStatus] = useState('')
  const [saving, setSaving] = useState(false)
  useEffect(() => { void Promise.all([getInterestQuestionnaire(), getInterestResult()]).then(([questionnaire, existing]) => { setItems(questionnaire.items); setRatings(existing.scores || Object.fromEntries(questionnaire.items.map((item) => [item.id, 50]))); if (existing.status !== 'not_started') setResult(existing) }).catch(() => setStatus('We could not load the interest check-in yet.')) }, [])
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setStatus(''); try { setResult(await submitInterestResponses(ratings, resultId)); setStatus('Saved. These interests are context, not a verdict.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'We could not save your interests.') } finally { setSaving(false) } }
  return <div className="page product-page"><ProductIntro eyebrow="Explore directions / Your interests" title={<>Tell us what you enjoy.<br /><em>Then see what to try.</em></>} body="This short check-in adds context after your cognitive profile. There are no right answers, and it does not change your assessment score." /><section className="panel interest-checkin"><div className="panel-top"><div><div className="eyebrow">RIASEC exploratory check-in</div><h2>Rate each statement</h2></div><span className="mono-label">0 = not me · 100 = very me</span></div><form onSubmit={submit}><div className="interest-slider-list">{items.map((item) => <label className="interest-slider" key={item.id}><span><b>{item.dimension}</b>{item.label}</span><output>{ratings[item.id] ?? 50}</output><input type="range" min="0" max="100" value={ratings[item.id] ?? 50} onChange={(event) => setRatings((current) => ({ ...current, [item.id]: Number(event.target.value) }))} aria-label={`${item.dimension}: ${item.label}`} /></label>)}</div><div className="product-form-footer"><button className="button primary" disabled={saving}>{saving ? 'Saving…' : 'Save my answers'} <span>→</span></button>{status && <span role="status" className="form-status">{status}</span>}</div></form></section>{result && <section className="panel interest-result"><div className="eyebrow">Your current interest pattern</div><div className="interest-code"><strong>{result.code || '—'}</strong><span>top three areas</span></div><div className="interest-result-bars">{Object.entries(result.scores || {}).sort(([, a], [, b]) => b - a).map(([code, score]) => <div key={code}><span>{code}</span><i><b style={{ width: `${score}%` }} /></i><strong>{score}</strong></div>)}</div><p>Use this as a prompt for real experiments. <Link to="/compass">Explore directions ↗</Link></p></section>}</div>
}

export function Certificates({ resultId }: { resultId?: string }) {
  const [certificates, setCertificates] = useState<Certificate[]>([])
  const [status, setStatus] = useState('')
  useEffect(() => { void listCertificates().then(setCertificates).catch(() => undefined) }, [])
  const issue = async () => { if (!resultId) return; setStatus(''); try { const certificate = await issueCertificate(resultId); setCertificates((current) => current.some((item) => item.id === certificate.id) ? current : [certificate, ...current]); setStatus('Certificate issued. You can verify it privately with its identifier.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'We could not issue a certificate.') } }
  return <div className="page product-page"><ProductIntro eyebrow="Your results / Completion record" title={<>Keep a record<br /><em>of your completed assessment.</em></>} body="This is a completion certificate, not an IQ qualification or population ranking. It contains no public score card." /><section className="panel certificate-panel"><div className="eyebrow">Private certificate</div><h2>{resultId ? 'Create a verifiable record.' : 'Complete a test first.'}</h2><p>{resultId ? 'Issue a certificate after your result is visible. The verification page shows only the minimum completion details.' : 'Your certificate becomes available after you submit a real assessment.'}</p><button className="button primary" disabled={!resultId} onClick={issue}>{resultId ? 'Issue certificate' : 'No result yet'} <span>→</span></button>{status && <p className="form-status" role="status">{status}</p>}</section>{certificates.length > 0 && <section className="panel certificate-list"><div className="eyebrow">Your certificates</div>{certificates.map((certificate) => <div className="certificate-row" key={certificate.id}><div><strong>{certificate.certificate_identifier}</strong><span>{certificate.title} · {new Date(certificate.issued_at).toLocaleDateString()}</span></div><Link className="text-button" to={`/verify?certificate=${certificate.certificate_identifier}`}>Verify ↗</Link></div>)}</section>}</div>
}

export function CertificateVerification() {
  const [params] = useSearchParams()
  const [identifier, setIdentifier] = useState(params.get('certificate') || '')
  const [result, setResult] = useState<{ valid: boolean; status: string; certificate_identifier: string; title?: string; assessment_version?: string; issued_at?: string } | null>(null)
  const [loading, setLoading] = useState(false)
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); try { setResult(await verifyCertificate(identifier)) } finally { setLoading(false) } }
  return <div className="page product-page"><ProductIntro eyebrow="IAQ / Verification" title={<>Check a certificate.<br /><em>See what it confirms.</em></>} body="Enter the certificate identifier. Verification confirms completion metadata only; it does not validate a normed IQ score." /><section className="panel verification-panel"><form className="verification-form" onSubmit={submit}><label>Certificate identifier<input value={identifier} onChange={(event) => setIdentifier(event.target.value.toUpperCase())} placeholder="IAQ-XXXXXXXXXX" required /></label><button className="button primary" disabled={loading}>{loading ? 'Checking…' : 'Check certificate'} <span>→</span></button></form>{result && <div className={`verification-result ${result.valid ? 'valid' : 'invalid'}`} role="status"><strong>{result.valid ? 'Certificate found' : 'No certificate found'}</strong><span>{result.valid ? `${result.title} · ${result.assessment_version} · issued ${result.issued_at ? new Date(result.issued_at).toLocaleDateString() : '—'}` : 'Check the identifier and try again.'}</span></div>}</section></div>
}

export function LegalPage({ title, body }: { title: string; body: string }) {
  return <div className="page legal-page"><ProductIntro eyebrow="IAQ / Policy" title={<>{title}.<br /><em>Plain language matters.</em></>} body={body} /><section className="panel policy-panel"><h2>What this means</h2><p>{body} IAQ keeps experimental results separate from official academic or clinical decisions. If you have a question about an order, account, consent, or report, use the feedback button or contact the team before relying on the information.</p><div className="policy-links"><Link to="/privacy">Read privacy ↗</Link><Link to="/methodology">Read methodology ↗</Link><Link to="/">Back to overview ↗</Link></div></section></div>
}

export function PublicInfoPage({ kind }: { kind: 'about' | 'sample' | 'schools' | 'help' | 'method' }) {
  const content = {
    about: { eyebrow: 'IAQ / About', title: <>A clearer start<br /><em>for what comes next.</em></>, body: 'IAQ helps students understand a small set of thinking signals, then connect them with interests and real experiments. It is designed to support conversations, not to label a person.' },
    sample: { eyebrow: 'IAQ / Sample report', title: <>See the report<br /><em>before you start.</em></>, body: 'A real report shows seven domain bars, the student’s own average, accuracy, timing context, confidence, and clear limits. It does not show a public percentile or make a destiny claim.' },
    schools: { eyebrow: 'IAQ / For schools', title: <>Give students context<br /><em>before advice.</em></>, body: 'Counselors get consent-aware access, cohort summaries, follow-up notes, and a clear separation between student-owned reports and school-level patterns.' },
    help: { eyebrow: 'IAQ / Help', title: <>Clear answers<br /><em>before you begin.</em></>, body: 'IAQ is a 35-minute, 56-question experimental educational profile. Results are private, provisional, and designed to be read with context.' },
    method: { eyebrow: 'IAQ / How it works', title: <>Test first.<br /><em>Read the evidence next.</em></>, body: 'A balanced form samples eight reviewed items from each of seven domains. The server enforces the deadline, scores responses, and keeps incomplete evidence visible.' },
  }[kind]
  return <div className="public-info-page"><nav className="public-info-nav"><Link to="/welcome" className="brand"><span className="brand-mark">i</span> IAQ<span className="brand-dot">.</span></Link><div><Link to="/how-it-works">How it works</Link><Link to="/assess">Assessments</Link><Link to="/for-schools">For schools</Link><Link to="/pricing">Pricing</Link><Link to="/auth/login">Sign in</Link><Link className="button primary" to="/assess">Start test <span>→</span></Link></div></nav><main className="public-info-main"><ProductIntro eyebrow={content.eyebrow} title={content.title} body={content.body} /><section className="public-info-evidence"><div className="public-info-block"><span className="eyebrow">01 / What you see</span><h2>Seven bars, one honest snapshot.</h2><p>Scores are shown within your own profile. If a domain has too little evidence, it stays unassessed instead of being filled with a reassuring number.</p></div><div className="public-info-block accent"><span className="eyebrow">02 / What comes next</span><h2>{kind === 'sample' ? 'Accuracy and timing stay visible.' : 'Use the result to choose a next experiment.'}</h2><p>{kind === 'schools' ? 'Access is role-based and consent-aware. A counselor cannot open a student report just because the student appears on a roster.' : 'Interests and directions are secondary context. They suggest things to try, not a fixed future.'}</p></div></section><div className="public-info-actions"><Link className="button primary" to="/assess">Start test <span>→</span></Link><Link className="text-button" to="/methodology">Read the methodology ↗</Link></div></main></div>
}
